"use client";
import { useMemo, useState } from "react";
import { supabase, supabaseReady } from "@/lib/supabase";
const tarifas:any={Enel:0.97,Light:0.844,Neoenergia:0.95,Copel:0.93,Energisa:0.89,Celesc:0.91,RGE:0.92,Cemig:0.88};
export default function SolarCalculator(){
 const [lead,setLead]=useState({nome:"",telefone:"",email:"",cidade:"",estado:"RJ",telhado:"ceramica",concessionaria:"Enel",conta:"350",quando:""});
 const [msg,setMsg]=useState(""); const [err,setErr]=useState("");
 const r=useMemo(()=>{const conta=Number(lead.conta||0),tarifa=tarifas[lead.concessionaria]||0.97;const consumo=conta/tarifa;const kwp=Math.max(1,consumo/0.78/5/30);const geracao=kwp*130;const investimento=kwp*2550;const economiaAno=conta*12*.86;const payback=economiaAno>0?investimento/economiaAno:0;return{consumo,kwp,geracao,investimento,economiaAno,payback}},[lead]);
 function set(k:string,v:string){setLead({...lead,[k]:v})}
 async function enviar(e:any){e.preventDefault();setMsg("");setErr(""); if(!supabaseReady||!supabase){setErr("Supabase não configurado. Verifique o .env.local.");return}
  const payload={nome:lead.nome,telefone:lead.telefone,email:lead.email,cidade:lead.cidade,conta_luz:Number(lead.conta),interesse:"Energia Solar Fotovoltaica",mensagem:`Simulação solar pelo site. Estado: ${lead.estado}. Concessionária: ${lead.concessionaria}. Telhado: ${lead.telhado}. Quando: ${lead.quando||"não informado"}. Consumo: ${r.consumo.toFixed(0)} kWh/mês. Sistema: ${r.kwp.toFixed(2)} kWp. Geração: ${r.geracao.toFixed(0)} kWh/mês. Investimento: R$ ${r.investimento.toFixed(2)}. Economia anual: R$ ${r.economiaAno.toFixed(2)}. Payback: ${r.payback.toFixed(1)} anos.`,consentimento_lgpd:true,origem:"site_calculadora",status:"novo"};
  const {error}=await supabase.from("leads").insert(payload); if(error){console.log(error);setErr(error.message);return} setMsg("Lead salvo com sucesso. Nossa equipe pode chamar no WhatsApp.")}
 const br=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
 return <div className="calc-grid"><form className="card form" onSubmit={enviar}><div className="grid2"><div className="field"><label>Nome</label><input className="input" required value={lead.nome} onChange={e=>set("nome",e.target.value)}/></div><div className="field"><label>WhatsApp</label><input className="input" required value={lead.telefone} onChange={e=>set("telefone",e.target.value)}/></div></div><div className="grid2"><div className="field"><label>E-mail</label><input className="input" type="email" value={lead.email} onChange={e=>set("email",e.target.value)}/></div><div className="field"><label>Cidade</label><input className="input" required value={lead.cidade} onChange={e=>set("cidade",e.target.value)}/></div></div><div className="grid2"><div className="field"><label>Concessionária</label><select className="input" value={lead.concessionaria} onChange={e=>set("concessionaria",e.target.value)}>{Object.keys(tarifas).map(t=><option key={t}>{t}</option>)}</select></div><div className="field"><label>Tipo de telhado</label><select className="input" value={lead.telhado} onChange={e=>set("telhado",e.target.value)}><option value="ceramica">Cerâmica</option><option value="fibrocimento">Fibrocimento</option><option value="metalico">Metálico</option><option value="laje">Laje</option></select></div></div><div className="grid2"><div className="field"><label>Conta média R$</label><input className="input" type="number" required value={lead.conta} onChange={e=>set("conta",e.target.value)}/></div><div className="field"><label>Quando pretende instalar?</label><input className="input" type="date" value={lead.quando} onChange={e=>set("quando",e.target.value)}/></div></div><button className="btn btn-blue" type="submit">Salvar lead e calcular</button>{msg&&<div className="lead-ok" style={{display:"block"}}>{msg}</div>}{err&&<div className="lead-err" style={{display:"block"}}>{err}</div>}<small>Ao enviar, você concorda com o contato comercial da ES Elétrica RJ conforme nossa política LGPD.</small></form><aside className="result"><h3>Resultado estimado</h3><div className="result-line"><span>Consumo mensal</span><b>{r.consumo.toFixed(0)} kWh</b></div><div className="result-line"><span>Sistema indicado</span><b>{r.kwp.toFixed(2)} kWp</b></div><div className="result-line"><span>Geração estimada</span><b>{r.geracao.toFixed(0)} kWh/mês</b></div><div className="result-line"><span>Investimento base</span><b>{br(r.investimento)}</b></div><div className="result-line"><span>Economia anual</span><b>{br(r.economiaAno)}</b></div><div className="result-line"><span>Payback estimado</span><b>{r.payback.toFixed(1)} anos</b></div><p style={{color:"#dbeafe"}}>Valores estimados. O projeto final depende de vistoria, padrão, telhado, homologação e equipamentos.</p><a className="btn btn-primary" href={`https://wa.me/5521998415889?text=${encodeURIComponent("Olá! Fiz uma simulação solar no site e quero atendimento.")}`} target="_blank">Falar com consultor</a></aside></div>
}
